# Generated by Django 4.2.2 on 2023-07-25 20:48

import charityapp.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.CharField(choices=[('BGN_10', '10 BGN'), ('BGN_20', '20 BGN'), ('BGN_50', '50 BGN'), ('BGN_100', '100 BGN'), ('BGN_200', '200 BGN'), ('BGN_OTHER', 'Other')], max_length=9)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('country', models.CharField(choices=[('COUNTRY', 'Bulgaria')])),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit card')])),
                ('holder_name', models.CharField()),
                ('card_verification_value', models.CharField(help_text='Enter the three-digit card verification value (CVV/CVC) from the back of your card.', max_length=3, validators=[charityapp.common.validators.validate_card_verification_value])),
                ('card_number', models.CharField(help_text='Enter the three-digit card verification value (CVV/CVC) from the back of your card.', max_length=19, validators=[charityapp.common.validators.validate_card_number])),
                ('card_expiration_month', models.CharField(choices=[('JANUARY', '1'), ('FEBRUARY', '2'), ('MARCH', '3'), ('APRIL', '4'), ('MAY', '5'), ('JUNE', '6'), ('JULY', '7'), ('AUGUST', '8'), ('SEPTEMBER', '9'), ('OCTOBER', '10'), ('NOVEMBER', '11'), ('DECEMBER', '12')], max_length=9)),
                ('card_expiration_year', models.CharField(choices=[('YEAR_23', '23'), ('YEAR_24', '24'), ('YEAR_25', '25'), ('YEAR_26', '26'), ('YEAR_27', '27'), ('YEAR_28', '28'), ('YEAR_29', '29'), ('YEAR_30', '30'), ('YEAR_31', '31'), ('YEAR_32', '32')], max_length=7)),
            ],
        ),
    ]
