# Generated by Django 4.2.3 on 2023-08-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RandomUserDonation',
            new_name='Donation',
        ),
    ]
