# Generated by Django 4.2.3 on 2023-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('resume', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('achievement_numbers', models.IntegerField()),
            ],
        ),
    ]
