# Generated by Django 4.2.3 on 2023-08-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusinfo',
            options={'verbose_name': 'Info about us', 'verbose_name_plural': 'Info about us'},
        ),
    ]
