# Generated by Django 4.2.3 on 2023-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='achievement_numbers',
            field=models.FloatField(),
        ),
    ]
