# Generated by Django 4.2.3 on 2023-08-10 17:50

import charityapp.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_donation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[charityapp.common.validators.validate_phone]),
        ),
    ]
