# Generated by Django 4.2.3 on 2023-08-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_latestnews_latestnew'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestNew',
            new_name='LatestNews',
        ),
    ]
