# Generated by Django 4.2.3 on 2023-08-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_latestnew_latestnews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impact',
            options={'verbose_name': 'Our Impact', 'verbose_name_plural': 'Our Impacts'},
        ),
        migrations.AlterModelOptions(
            name='latestnews',
            options={'verbose_name_plural': 'Latest News'},
        ),
    ]
