# Generated by Django 4.2.3 on 2023-08-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_donation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_amount',
            field=models.CharField(choices=[('BGN_10', '10 BGN'), ('BGN_20', '20 BGN'), ('BGN_50', '50 BGN'), ('BGN_100', '100 BGN'), ('BGN_200', '200 BGN'), ('BGN_500', '500 BGN'), ('BGN_1000', '1000 BGN'), ('BGN_1500', '1500 BGN')], max_length=8),
        ),
    ]
