# Generated by Django 4.2.3 on 2023-08-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_impact_options_alter_latestnews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusinfo',
            options={'verbose_name': 'Info About Us', 'verbose_name_plural': 'Info About Us'},
        ),
        migrations.AlterModelOptions(
            name='impact',
            options={'verbose_name': 'Our Impact', 'verbose_name_plural': 'Our Impact'},
        ),
    ]
