# Generated by Django 4.2.3 on 2023-08-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_aboutusinfo_options_alter_impact_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donation',
            new_name='RandomUserDonation',
        ),
    ]
