# Generated by Django 4.2.3 on 2023-07-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
