# Generated by Django 4.2.3 on 2023-08-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='allow_posting',
            field=models.BooleanField(default=False),
        ),
    ]
