# Generated by Django 4.2.3 on 2023-08-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
