# Generated by Django 4.2.3 on 2023-08-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsordonation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='campaigns',
            field=models.ManyToManyField(related_name='q_and_a', to='causes.charitycampaign'),
        ),
    ]
