# Generated by Django 4.2.3 on 2023-08-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcampaigns',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
    ]
