# Generated by Django 4.2.3 on 2023-08-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_rename_donationcampaigns_donationcampaign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQCampaigns',
            new_name='FAQCampaign',
        ),
    ]
