# Generated by Django 4.2.3 on 2023-08-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_rename_faqcampaigns_faqcampaign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQCampaign',
            new_name='FAQ',
        ),
    ]
