# Generated by Django 4.2.3 on 2023-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_rename_faqcampaign_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charitycampaign',
            options={'verbose_name': 'Charity Campaign', 'verbose_name_plural': 'Charity Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='donationcampaign',
            options={'verbose_name': 'Donation Campaign', 'verbose_name_plural': 'Donation Campaigns'},
        ),
        migrations.AddField(
            model_name='charitycampaign',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
