# Generated by Django 4.2.3 on 2023-08-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_charitycampaign_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationcampaign',
            old_name='motivation',
            new_name='purpose',
        ),
    ]
