# Generated by Django 4.2.3 on 2023-08-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_alter_donationcampaign_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
