# Generated by Django 4.2.3 on 2023-08-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_donationcampaign_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
