# Generated by Django 4.2.3 on 2023-08-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_alter_donationcampaign_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
