# Generated by Django 4.2.3 on 2023-08-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_alter_donationcampaign_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcampaign',
            name='logo',
        ),
    ]
