# Generated by Django 4.2.3 on 2023-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_donationcampaign_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaign',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
