# Generated by Django 4.2.3 on 2023-08-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'verbose_name': 'Member Profile', 'verbose_name_plural': 'Members Profile'},
        ),
        migrations.AlterModelOptions(
            name='sponsorprofile',
            options={'verbose_name': 'Sponsor Profile', 'verbose_name_plural': 'Sponsors Profile'},
        ),
        migrations.AlterModelOptions(
            name='volunteerprofile',
            options={'verbose_name': 'Volunteer Profile', 'verbose_name_plural': 'Volunteers Profile'},
        ),
    ]
