# Generated by Django 4.2.2 on 2023-07-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_remove_memberprofile_id_remove_sponsorprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
