# Generated by Django 4.2.3 on 2023-08-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_alter_memberprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='donation_history',
        ),
    ]
