# Generated by Django 4.2.2 on 2023-07-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_alter_volunteerprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
