# Generated by Django 4.2.3 on 2023-07-27 22:43

import charityapp.user_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
        ('user_profiles', '0005_alter_memberprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='contribution_history',
            field=models.ManyToManyField(to='work.charitycampaigns', verbose_name='YOUR CONTRIBUTION HISTORY'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('DO_NOT_SHOW', 'Do not show')], default=charityapp.user_profiles.models.Gender['DO_NOT_SHOW'], max_length=30, verbose_name='YOUR GENDER'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='interests',
            field=models.CharField(choices=[('ENVIRONMENTAL_CAUSES', 'Environmental causes'), ('HUMANITARIAN_CAUSES', 'Humanitarian causes'), ('DISASTERS_AND_ACCIDENTS_CAUSES', 'Causes of disasters and accidents'), ('ANIMAL_CAUSES', 'Animal causes'), ('OTHER', 'Other')], max_length=30, verbose_name='YOUR INTERESTS'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='phone_number',
            field=models.CharField(blank=True, null=True, verbose_name='YOUR PHONE'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('CHAIRMAN', 'Chairman'), ('VICE_CHAIRMAN', 'Vice Chairman'), ('SECRETARY', 'Secretary'), ('ADMINISTRATOR', 'Administrator'), ('MODERATOR', 'Moderator'), ('CASHIER', 'Cashier'), ('PR', 'Public Relations (PR)'), ('OTHER', 'Other')], max_length=13, verbose_name='YOUR ROLE IN THE CLUB'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='strengths',
            field=models.TextField(blank=True, null=True, verbose_name='YOUR STRENGTHS'),
        ),
        migrations.AlterField(
            model_name='sponsorprofile',
            name='career_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CAREER FIELD'),
        ),
        migrations.AlterField(
            model_name='sponsorprofile',
            name='donation_history',
            field=models.ManyToManyField(to='work.donationcampaigns', verbose_name='DONATION HISTORY'),
        ),
    ]
