# Generated by Django 4.2.3 on 2023-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
        ('user_profiles', '0007_alter_memberprofile_contribution_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='contribution_history',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='charity_history',
            field=models.ManyToManyField(to='work.charitycampaigns', verbose_name='MY CHARITY HISTORY'),
        ),
    ]
