# Generated by Django 4.2.3 on 2023-07-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0009_memberprofile_created_at_sponsorprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sponsorprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='created_at',
        ),
    ]
