# Generated by Django 4.2.3 on 2023-07-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0011_alter_memberprofile_charity_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='ABOUT'),
        ),
    ]
